name: Secret Scan with Gitleaks

on:
  push:
    branches:
      - "**"  # Runs on all branches
  pull_request:
    branches:
      - "**"  # Runs on all pull requests

jobs:
  gitleaks_scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history for scanning

      - name: Install Gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.23.3/gitleaks_8.23.3_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          sudo mv gitleaks /usr/local/bin/
          rm gitleaks.tar.gz

      - name: Run Gitleaks Scan
        id: gitleaks
        run: |
          gitleaks detect --verbose --redact --report-format=json --report-path=gitleaks-report.json || echo "Gitleaks detected secrets!"

      - name: Check for keyword "techopsapex"
        run: |
          if git log -p | grep -i "techopsapex"; then
            echo "❌ Commit contains 'techopsapex'. Please review!"
          else
            echo "✅ No keyword 'techopsapex' found."
          fi

      - name: Upload Gitleaks Report (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
